# Generated by Django 4.0.4 on 2022-05-30 09:38

from django.db import migrations, models
import uploadme.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=uploadme.models.upload_path),
        ),
    ]
